name: Deploy QuizSpar

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: quizspark-frontend
  BACKEND_URL: https://your-backend-domain.com  # Update this with your actual backend URL

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build frontend
        run: |
          # Create .env.production file with backend URL
          echo "VITE_API_URL=${{ env.BACKEND_URL }}" > .env.production
          npm run build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: List S3 buckets
        run: aws s3 ls
        
      - name: Check bucket exists
        run: aws s3 ls s3://${{ env.S3_BUCKET }} || echo "Bucket does not exist or no access"
        
      - name: Set bucket policy for public access
        run: |
          cat > bucket-policy.json << EOF
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Sid": "PublicReadGetObject",
                      "Effect": "Allow",
                      "Principal": "*",
                      "Action": "s3:GetObject",
                      "Resource": "arn:aws:s3:::${{ env.S3_BUCKET }}/*"
                  }
              ]
          }
          EOF
          aws s3api put-bucket-policy --bucket ${{ env.S3_BUCKET }} --policy file://bucket-policy.json
        
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ env.S3_BUCKET }} --delete

  verify-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r fastapi_backend/requirements.txt
          pip install email-validator
          pip install -e .
          
      - name: Verify FastAPI server
        run: |
          python -c "from fastapi_backend.main import app; print('FastAPI server imports successfully')" 